services:
  smart-trader-app:
    container_name: smart-trader-app
    restart: always
    build:
      context: .
    networks:
      - db_network
      - web_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.docker
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - smart-trader-app
  redis:
    image: redis:7.0.12
    container_name: redis
    command: ["redis-server", "--port", "6379", "--slave-read-only", "no"]
    restart: always
    ports:
      - 6379:6379
    networks:
      - db_network
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    networks:
      - db_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
    command: "celery -A apps.tasks worker -l info -B"
    depends_on:
      - smart-trader-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
